### ISSUE TITLE
Go 1.5 Vendoring?

### ISSUE THREAD

**Issue by pib** [mediocregopher/goat#30]
Go 1.5 adds experimental support for vendoring: https://docs.google.com/document/d/1Bz5-UB7g2uPBdOx-rw5t9MxJwkfpx90cqG9AFL0JAYo/edit

I feel like it would make sense to support this layout somehow in goat. Perhaps an option in the .go.yaml file that would tell goat to use that layout and that would cause it to put deps in the vendor directory instead of the .goat deps directory. It would also cause goat to set the `GO15VENDOREXPERIMENT=1` environment variable rather than `GOPATH`.

Of course, assuming the root directory is not inside a properly laid-out GOPATH it would potentially also be necessary to still create one in the .goat directory just so the repo could be symlinked into a GOPATH.

For users who keep their code inside a GOPATH, it may make sense to allow the .goat directory generation to be disabled as well?

I like the way goat works currently, but it seems that the Go community is moving in a different direction with the way dependencies are handled, so I'm trying to figure out how to get the two to work nicely together.

**Comment by mediocregopher** [comment]
Hey pib! To be honest I stopped using goat some time ago, and have just been doing things the recommended global `$GOPATH` way. It's been less hassle for me in a lot of ways, so I don't see myself going back. That said I don't think I'll be working on goat much anymore, especially with the vendoring tool almost being built in at this point. If you'd like to fork the project and continue working on it please feel free though, I'd be happy to add a note to the README pointing potential newcomers your way.

**Comment by trans** [comment]
I find the direction Go is taking rather disappointing. The length of paths caused by layers of vedoring this can create is rather ridiculous. But is their any point in fighting it? I am not sure. But if I had to choose, at this point, I would still prefer to use goat as is. But it doesn't make much difference to me at this point either. As with @mediocregopher I have moved on, but in a more drastic way. After some initial work in Go I was less than impressed with its speed. And having come to the conclusion that Go would never support generics, I finally decided Go wasn't the language for me. I am disappointed by that b/c I did enjoy much about the language. I won't totally swear it off at this point, but it is enitely possible I will never program in Go again.

Even so, I don't think this proposal is a good idea b/c it just doesn't fit with the *Way of the Goat*. I'd much rather see it remain as is, offering a true alternative to the mainstream approach. Let all the other vendoring wannabes fumble over themselves adding support for this poor standard. The Goat does not care.
